### ISSUE TITLE
Bug: Change Password page incomplete

### ISSUE THREAD

**Issue by theechosensloth** [Darkmono112/Hacksmith2023#72] opened 2023-11-20 17:59 UTC
1. start project
2. navigate to http://localhost:8000
3. navigate to http://localhost:8000/change_username

** Should take user to a page where they can change their password **

**Comment by paigem33** [comment] 2023-11-29 04:25
Closing, is a duplicate of #69

**Closed by paigem33** 2023-11-29 04:25 UTC
